sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: learning-take-out
    access-key-secret: hHMNZxf7gZtgaFfwHolDIH86U4uJEA
    access-key-id: LTAI5tB9SE91448KAUBAGTAi
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  wechat:
    appid: wxc47228bd9848a634
    secret: f9d51f32943aa406f7950e2666bf2375
    mchid: 1561414331
    mchSerialNo: 432423412983feshf433214g12g4
    privateKeyFilePath:
    apiV3Key:
    weChatPayCertFilePath:
    notifyUrl:
    refundNotifyUrl:
