sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: learning-take-out
    access-key-secret: hHMNZxf7gZtgaFfwHolDIH86U4uJEA
    access-key-id: LTAI5tB9SE91448KAUBAGTAi